/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChecaPedidosController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.JTableHeader;


public class ChecaPedidos extends javax.swing.JFrame {

    private final ChecaPedidosController controller;
    
    public ChecaPedidos() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(161, 183, 198));
        VerificarBtn.setBackground(Color.white);
        
        JcomboClientes.setBackground(Color.white);
        
        TabelaPedidos.getTableHeader().setOpaque(false);
        TabelaPedidos.getTableHeader().setBackground(Color.red);
        
        jScrollPane1.getViewport().setBackground(new java.awt.Color(170, 195, 209));
        
        JTableHeader header = TabelaPedidos.getTableHeader();
        header.setBackground(Color.blue);  // Cor do cabeçalho
        header.setForeground(Color.black);      // Cor do texto do cabeçalho
        
        
        controller = new ChecaPedidosController(this);
        try {
            controller.adicionarAoComboBox(JcomboClientes);
        } catch (SQLException ex) {
            Logger.getLogger(ChecaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        JcomboClientes = new javax.swing.JComboBox<>();
        VerificarBtn = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        VoltarTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedidos");

        TabelaPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Pedido", "Id Item", "Nome Item", "Preço"
            }
        ));
        jScrollPane1.setViewportView(TabelaPedidos);

        JcomboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcomboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboClientesActionPerformed(evt);
            }
        });

        VerificarBtn.setText("Verificar");
        VerificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarBtnActionPerformed(evt);
            }
        });

        Texto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        VoltarTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow-alt-regular-48.png"))); // NOI18N
        VoltarTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarTelaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VoltarTela, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JcomboClientes, 0, 255, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(VerificarBtn)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JcomboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VerificarBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VoltarTela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Pedidos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JcomboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboClientesActionPerformed
       
    }//GEN-LAST:event_JcomboClientesActionPerformed

    private void VerificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarBtnActionPerformed
        try {
            controller.ChamaPedidos();
            controller.adicionarATabela(TabelaPedidos);
        } catch (SQLException ex) {
            Logger.getLogger(ChecaPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        String selectedNome = getJcomboClientes().getSelectedItem().toString();
        
        int index = selectedNome.indexOf('|');
        String nome;        
        if (index != -1) {
        nome= selectedNome.substring(index+1);
            Texto.setText("Pedidos de"+ nome);
            } else {
                System.out.println("Caractere não encontrado na string.");
            }
        
    }//GEN-LAST:event_VerificarBtnActionPerformed

    private void VoltarTelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarTelaMouseClicked

        new TelaDeMenu().setVisible(true);

        dispose();
    }//GEN-LAST:event_VoltarTelaMouseClicked

    public JComboBox<String> getJcomboClientes() {
        return JcomboClientes;
    }

    public void setJcomboClientes(JComboBox<String> JcomboClientes) {
        this.JcomboClientes = JcomboClientes;
    }

    public JTable getTabelaPedidos() {
        return TabelaPedidos;
    }

    public void setTabelaPedidos(JTable TabelaPedidos) {
        this.TabelaPedidos = TabelaPedidos;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChecaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChecaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChecaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChecaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChecaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcomboClientes;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JLabel Texto;
    private javax.swing.JButton VerificarBtn;
    private javax.swing.JLabel VoltarTela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
