/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ClientesController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author bielg
 */
public class Clientes extends javax.swing.JFrame {

    private final ClientesController controller;

    /**
     * Creates new form TelaDeClientes
     */
    public Clientes() {
        initComponents();
        
        controller = new ClientesController(this);
        
        try {
            controller.adicionarATabela(TabelaClientes);
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InsertNomeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InsertEmailC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InsertEmailC2 = new javax.swing.JTextField();
        InsertEmailC3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("Excluir");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRAR CLIENTES");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel2.setText("TABELA DE CLIENTES");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        InsertNomeC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertNomeC.setForeground(new java.awt.Color(153, 153, 153));
        InsertNomeC.setText("Nome Completo...");
        InsertNomeC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertNomeCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertNomeCFocusLost(evt);
            }
        });
        InsertNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertNomeCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Endereço:");

        InsertEmailC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertEmailC.setForeground(new java.awt.Color(153, 153, 153));
        InsertEmailC.setText("Email...");
        InsertEmailC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertEmailCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertEmailCFocusLost(evt);
            }
        });
        InsertEmailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmailCActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");

        InsertEmailC2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertEmailC2.setForeground(new java.awt.Color(153, 153, 153));
        InsertEmailC2.setText("Telefone...");
        InsertEmailC2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertEmailC2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertEmailC2FocusLost(evt);
            }
        });
        InsertEmailC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmailC2ActionPerformed(evt);
            }
        });

        InsertEmailC3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertEmailC3.setForeground(new java.awt.Color(153, 153, 153));
        InsertEmailC3.setText("CPF...");
        InsertEmailC3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertEmailC3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertEmailC3FocusLost(evt);
            }
        });
        InsertEmailC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmailC3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CEP:");

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton2.setText("Adicionar");
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jButton3.setText("Alterar");
        jButton3.setAlignmentY(0.0F);
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "nome", "endereço", "cep", "telefone"
            }
        ));
        jScrollPane1.setViewportView(TabelaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertEmailC3)
                    .addComponent(InsertEmailC)
                    .addComponent(InsertEmailC2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(InsertNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(InsertNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(InsertEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(InsertEmailC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(InsertEmailC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InsertNomeCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeCFocusGained

        if(InsertNomeC.getText().equals("Nome Completo")){

            InsertNomeC.setText("");
            InsertNomeC.setForeground(new Color(0, 0, 0));

        }

    }//GEN-LAST:event_InsertNomeCFocusGained

    private void InsertNomeCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeCFocusLost

        if(InsertNomeC.getText().equals("")){

            InsertNomeC.setText("Nome Completo");
            InsertNomeC.setForeground(new Color(153, 153, 153));

        }

    }//GEN-LAST:event_InsertNomeCFocusLost

    private void InsertNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertNomeCActionPerformed

    private void InsertEmailCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailCFocusGained

        if(InsertEmailC.getText().equals("Email")){

            InsertEmailC.setText("");
            InsertEmailC.setForeground(new Color(0, 0, 0));

        }

    }//GEN-LAST:event_InsertEmailCFocusGained

    private void InsertEmailCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailCFocusLost

        if(InsertEmailC.getText().equals("")){

            InsertEmailC.setText("Email");
            InsertEmailC.setForeground(new Color(153, 153, 153));

        }

    }//GEN-LAST:event_InsertEmailCFocusLost

    private void InsertEmailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailCActionPerformed

    private void InsertEmailC2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailC2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC2FocusGained

    private void InsertEmailC2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailC2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC2FocusLost

    private void InsertEmailC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmailC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC2ActionPerformed

    private void InsertEmailC3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailC3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC3FocusGained

    private void InsertEmailC3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailC3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC3FocusLost

    private void InsertEmailC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmailC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailC3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public JTable getTabelaClientes() {
        return TabelaClientes;
    }

    public void setTabelaClientes(JTable TabelaClientes) {
        this.TabelaClientes = TabelaClientes;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsertEmailC;
    private javax.swing.JTextField InsertEmailC2;
    private javax.swing.JTextField InsertEmailC3;
    private javax.swing.JTextField InsertNomeC;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
