/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ClientesController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Item_Estoque;

/**
 *
 * @author bielg
 */
public class Clientes extends javax.swing.JFrame {

    private final ClientesController controller;
    private int selectedId;

    /**
     * Creates new form TelaDeClientes
     */
    public Clientes() {
        initComponents();
        
        controller = new ClientesController(this);
        
        try {
            controller.adicionarATabela(TabelaClientes);
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InsertNomeCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        InsertEndCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InsertTeleCliente = new javax.swing.JTextField();
        InsertCepClientes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        VoltarTela = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        InsertCPFCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnExcluir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setAlignmentY(0.0F);
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRAR CLIENTES");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel2.setText("TABELA DE CLIENTES");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        InsertNomeCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertNomeCliente.setForeground(new java.awt.Color(153, 153, 153));
        InsertNomeCliente.setText("Nome Completo");
        InsertNomeCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertNomeClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertNomeClienteFocusLost(evt);
            }
        });
        InsertNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertNomeClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Endereço:");

        InsertEndCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertEndCliente.setForeground(new java.awt.Color(153, 153, 153));
        InsertEndCliente.setText("Endereço");
        InsertEndCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertEndClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertEndClienteFocusLost(evt);
            }
        });
        InsertEndCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEndClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefone:");

        InsertTeleCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertTeleCliente.setForeground(new java.awt.Color(153, 153, 153));
        InsertTeleCliente.setText("Telefone");
        InsertTeleCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertTeleClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertTeleClienteFocusLost(evt);
            }
        });
        InsertTeleCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTeleClienteActionPerformed(evt);
            }
        });

        InsertCepClientes.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertCepClientes.setForeground(new java.awt.Color(153, 153, 153));
        InsertCepClientes.setText("CEP");
        InsertCepClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertCepClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertCepClientesFocusLost(evt);
            }
        });
        InsertCepClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertCepClientesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CEP:");

        VoltarTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow-alt-regular-48.png"))); // NOI18N
        VoltarTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarTelaMouseClicked(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setAlignmentY(0.0F);
        btnAdicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setAlignmentY(0.0F);
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CPF");

        InsertCPFCliente.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        InsertCPFCliente.setForeground(new java.awt.Color(153, 153, 153));
        InsertCPFCliente.setText("CPF");
        InsertCPFCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertCPFClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertCPFClienteFocusLost(evt);
            }
        });
        InsertCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertCPFClienteActionPerformed(evt);
            }
        });

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_cliente", "nome", "endereço", "cep", "telefone", "cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InsertTeleCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsertEndCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsertCepClientes)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(InsertNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(InsertCPFCliente))
                                .addGap(103, 103, 103))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VoltarTela, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VoltarTela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(InsertNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(InsertEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(InsertCepClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(InsertTeleCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(InsertCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            controller.excluirCliente(selectedId);
            controller.adicionarATabela(TabelaClientes);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void InsertNomeClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeClienteFocusGained

        if(InsertNomeCliente.getText().equals("Nome Completo")){

            InsertNomeCliente.setText("");
            InsertNomeCliente.setForeground(new Color(0, 0, 0));

        }

    }//GEN-LAST:event_InsertNomeClienteFocusGained

    private void InsertNomeClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeClienteFocusLost

        if(InsertNomeCliente.getText().equals("")){

            InsertNomeCliente.setText("Nome Completo");
            InsertNomeCliente.setForeground(new Color(153, 153, 153));

        }

    }//GEN-LAST:event_InsertNomeClienteFocusLost

    private void InsertNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertNomeClienteActionPerformed

    private void InsertEndClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEndClienteFocusGained

        if(InsertEndCliente.getText().equals("Endereço")){

            InsertEndCliente.setText("");
            InsertEndCliente.setForeground(new Color(0, 0, 0));

        }

    }//GEN-LAST:event_InsertEndClienteFocusGained

    private void InsertEndClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEndClienteFocusLost

        if(InsertEndCliente.getText().equals("")){

            InsertEndCliente.setText("Endereço");
            InsertEndCliente.setForeground(new Color(153, 153, 153));

        }

    }//GEN-LAST:event_InsertEndClienteFocusLost

    private void InsertEndClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEndClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEndClienteActionPerformed

    private void InsertTeleClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertTeleClienteFocusGained
        if(InsertTeleCliente.getText().equals("Telefone")){

            InsertTeleCliente.setText("");
            InsertTeleCliente.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_InsertTeleClienteFocusGained

    private void InsertTeleClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertTeleClienteFocusLost
        if(InsertTeleCliente.getText().equals("")){

            InsertTeleCliente.setText("Telefone");
            InsertTeleCliente.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_InsertTeleClienteFocusLost

    private void InsertTeleClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTeleClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertTeleClienteActionPerformed

    private void InsertCepClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertCepClientesFocusGained
        if(InsertCepClientes.getText().equals("CEP")){

            InsertCepClientes.setText("");
            InsertCepClientes.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_InsertCepClientesFocusGained

    private void InsertCepClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertCepClientesFocusLost
        if(InsertCepClientes.getText().equals("")){

            InsertCepClientes.setText("CEP");
            InsertCepClientes.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_InsertCepClientesFocusLost

    private void InsertCepClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertCepClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertCepClientesActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            controller.SalvarCliente();
            controller.adicionarATabela(TabelaClientes);
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        DefaultTableModel model = (DefaultTableModel) TabelaClientes.getModel();
        int selectedRowIndex = TabelaClientes.getSelectedRow();

        if (selectedRowIndex != -1) { // Verifica se uma linha está selecionada
            int id = (int) model.getValueAt(selectedRowIndex, 0);
            String nome = InsertNomeCliente.getText();
            String endereco = InsertEndCliente.getText();
            int cep = Integer.parseInt(InsertCepClientes.getText());
            String telefone = InsertTeleCliente.getText();
            Double cpf = Double.valueOf(InsertCPFCliente.getText());

            Cliente cliente = new Cliente(id, nome, endereco, cep, telefone, cpf);

            try {
                controller.updateCliente(cliente);
                controller.adicionarATabela(TabelaClientes);
            } catch (SQLException ex) {
                Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar.");
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void InsertCPFClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertCPFClienteFocusGained
        if(InsertCPFCliente.getText().equals("CPF")){

            InsertCPFCliente.setText("");
            InsertCPFCliente.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_InsertCPFClienteFocusGained

    private void InsertCPFClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertCPFClienteFocusLost
        if(InsertCPFCliente.getText().equals("")){

            InsertCPFCliente.setText("CPF");
            InsertCPFCliente.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_InsertCPFClienteFocusLost

    private void InsertCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertCPFClienteActionPerformed

    private void VoltarTelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarTelaMouseClicked

        new TelaDeMenu().setVisible(true);
        
        dispose();

    }//GEN-LAST:event_VoltarTelaMouseClicked

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        DefaultTableModel model = (DefaultTableModel)TabelaClientes.getModel();
        int selectedRowIndex = TabelaClientes.getSelectedRow();
        
        selectedId = (int) model.getValueAt(selectedRowIndex, 0);
        
        InsertNomeCliente.setText(model.getValueAt(selectedRowIndex, 1).toString());
        InsertEndCliente.setText(model.getValueAt(selectedRowIndex, 2).toString());
        InsertCepClientes.setText(model.getValueAt(selectedRowIndex, 3).toString());
        InsertTeleCliente.setText(model.getValueAt(selectedRowIndex, 4).toString());
        InsertCPFCliente.setText(model.getValueAt(selectedRowIndex, 5).toString());
         
        //mostraId.setText("Id Selecionado: " + selectedId);
    }//GEN-LAST:event_TabelaClientesMouseClicked

    public JTable getTabelaClientes() {
        return TabelaClientes;
    }

    public void setTabelaClientes(JTable TabelaClientes) {
        this.TabelaClientes = TabelaClientes;
    }

    public JTextField getInsertCepClientes() {
        return InsertCepClientes;
    }

    public void setInsertCepClientes(JTextField InsertCepClientes) {
        this.InsertCepClientes = InsertCepClientes;
    }

    public JTextField getInsertEndCliente() {
        return InsertEndCliente;
    }

    public void setInsertEndCliente(JTextField InsertEndCliente) {
        this.InsertEndCliente = InsertEndCliente;
    }

    public JTextField getInsertNomeCliente() {
        return InsertNomeCliente;
    }

    public void setInsertNomeCliente(JTextField InsertNomeCliente) {
        this.InsertNomeCliente = InsertNomeCliente;
    }

    public JTextField getInsertTeleCliente() {
        return InsertTeleCliente;
    }

    public void setInsertTeleCliente(JTextField InsertTeleCliente) {
        this.InsertTeleCliente = InsertTeleCliente;
    }

    public JTextField getInsertCPFCliente() {
        return InsertCPFCliente;
    }

    public void setInsertCPFCliente(JTextField InsertCPFCliente) {
        this.InsertCPFCliente = InsertCPFCliente;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsertCPFCliente;
    private javax.swing.JTextField InsertCepClientes;
    private javax.swing.JTextField InsertEndCliente;
    private javax.swing.JTextField InsertNomeCliente;
    private javax.swing.JTextField InsertTeleCliente;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JLabel VoltarTela;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
