/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bielg
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeClientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        GerenciarMenu = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenu();
        AdicionarCliente = new javax.swing.JMenuItem();
        AlterarCliente = new javax.swing.JMenuItem();
        RemoverCliente = new javax.swing.JMenuItem();
        Estoque = new javax.swing.JMenu();
        AlterarEstoque = new javax.swing.JMenuItem();
        AdicionarEstoque = new javax.swing.JMenuItem();
        RemoverEstoque = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Cliente");

        GerenciarMenu.setText("Gerenciar");
        GerenciarMenu.setToolTipText("");

        Cliente.setText("Cliente");

        AdicionarCliente.setText("Adicionar");
        AdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarClienteActionPerformed(evt);
            }
        });
        Cliente.add(AdicionarCliente);

        AlterarCliente.setText("Alterar");
        Cliente.add(AlterarCliente);

        RemoverCliente.setText("Remover");
        RemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverClienteActionPerformed(evt);
            }
        });
        Cliente.add(RemoverCliente);

        GerenciarMenu.add(Cliente);

        Estoque.setText("Estoque");

        AlterarEstoque.setText("Alterar");
        Estoque.add(AlterarEstoque);

        AdicionarEstoque.setText("Adicionar");
        AdicionarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarEstoqueActionPerformed(evt);
            }
        });
        Estoque.add(AdicionarEstoque);

        RemoverEstoque.setText("Remover");
        RemoverEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverEstoqueActionPerformed(evt);
            }
        });
        Estoque.add(RemoverEstoque);

        GerenciarMenu.add(Estoque);

        jMenuBar1.add(GerenciarMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdicionarClienteActionPerformed

    private void RemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverClienteActionPerformed

    private void AdicionarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdicionarEstoqueActionPerformed

    private void RemoverEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarCliente;
    private javax.swing.JMenuItem AdicionarEstoque;
    private javax.swing.JMenuItem AlterarCliente;
    private javax.swing.JMenuItem AlterarEstoque;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Estoque;
    private javax.swing.JMenu GerenciarMenu;
    private javax.swing.JMenuItem RemoverCliente;
    private javax.swing.JMenuItem RemoverEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
