package view;


import controller.TelaDeCadastroController;
import java.sql.Connection;
import dao.Conexao;
import dao.UsuarioDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.Usuario;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luizd
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    private final TelaDeCadastroController controller;
    
    public TelaDeCadastro() {
        initComponents();
        controller = new TelaDeCadastroController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InsertNomeC = new javax.swing.JTextField();
        InsertEmailC = new javax.swing.JTextField();
        InsertSenhaC = new javax.swing.JPasswordField();
        InsertConfSenhaC = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CadastrarTela2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro");

        InsertNomeC.setForeground(new java.awt.Color(153, 153, 153));
        InsertNomeC.setText("Nome Completo");
        InsertNomeC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertNomeCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertNomeCFocusLost(evt);
            }
        });
        InsertNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertNomeCActionPerformed(evt);
            }
        });

        InsertEmailC.setForeground(new java.awt.Color(153, 153, 153));
        InsertEmailC.setText("Email");
        InsertEmailC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertEmailCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertEmailCFocusLost(evt);
            }
        });
        InsertEmailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertEmailCActionPerformed(evt);
            }
        });

        InsertSenhaC.setForeground(new java.awt.Color(153, 153, 153));
        InsertSenhaC.setText("Senha");
        InsertSenhaC.setEchoChar('\u0000');
        InsertSenhaC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertSenhaCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertSenhaCFocusLost(evt);
            }
        });
        InsertSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertSenhaCActionPerformed(evt);
            }
        });

        InsertConfSenhaC.setForeground(new java.awt.Color(153, 153, 153));
        InsertConfSenhaC.setText("Confirmar Senha");
        InsertConfSenhaC.setEchoChar('\u0000');
        InsertConfSenhaC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InsertConfSenhaCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InsertConfSenhaCFocusLost(evt);
            }
        });
        InsertConfSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertConfSenhaCActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Email:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmar Senha:");

        CadastrarTela2.setText("Cadastrar");
        CadastrarTela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarTela2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InsertNomeC)
                                .addComponent(InsertEmailC)
                                .addComponent(InsertSenhaC)
                                .addComponent(InsertConfSenhaC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(CadastrarTela2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(InsertNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(InsertEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(InsertSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertConfSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastrarTela2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertNomeCActionPerformed

    private void InsertNomeCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeCFocusGained
         
        if(InsertNomeC.getText().equals("Nome Completo")){
        
            InsertNomeC.setText("");
            InsertNomeC.setForeground(new Color(0, 0, 0));
        
        }
        
    }//GEN-LAST:event_InsertNomeCFocusGained

    private void InsertNomeCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertNomeCFocusLost
        
        if(InsertNomeC.getText().equals("")){
        
            InsertNomeC.setText("Nome Completo");
            InsertNomeC.setForeground(new Color(153, 153, 153));
        
        }
        
    }//GEN-LAST:event_InsertNomeCFocusLost

    private void InsertEmailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertEmailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertEmailCActionPerformed

    private void InsertSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertSenhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertSenhaCActionPerformed

    private void InsertEmailCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailCFocusGained
        
        if(InsertEmailC.getText().equals("Email")){
        
            InsertEmailC.setText("");
            InsertEmailC.setForeground(new Color(0, 0, 0));
        
        }
        
    }//GEN-LAST:event_InsertEmailCFocusGained

    private void InsertEmailCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertEmailCFocusLost
        
        if(InsertEmailC.getText().equals("")){
        
            InsertEmailC.setText("Email");
            InsertEmailC.setForeground(new Color(153, 153, 153));
        
        }
        
    }//GEN-LAST:event_InsertEmailCFocusLost

    private void CadastrarTela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarTela2ActionPerformed
         controller.salvaUsuario();
        
        
        
    }//GEN-LAST:event_CadastrarTela2ActionPerformed

    private void InsertSenhaCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertSenhaCFocusGained
        
        if(new String (InsertSenhaC.getPassword()).equals("Senha")){
        
            InsertSenhaC.setText(null);
            InsertSenhaC.requestFocus();
            
            InsertSenhaC.setEchoChar('*');
            
            InsertSenhaC.setForeground(new Color(0, 0, 0));
        
        }
        
    }//GEN-LAST:event_InsertSenhaCFocusGained

    private void InsertSenhaCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertSenhaCFocusLost
        
        if(new String (InsertSenhaC.getPassword()).equals("")){
        
            InsertSenhaC.setText("Senha");
            InsertSenhaC.setForeground(new Color(0, 0, 0));
            
        }
        if(new String (InsertSenhaC.getPassword()).equals("Senha")){
        
            InsertSenhaC.setEchoChar('\u0000');
            InsertSenhaC.setForeground(new Color(153, 153, 153));
            
        }
        
    }//GEN-LAST:event_InsertSenhaCFocusLost

    private void InsertConfSenhaCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertConfSenhaCFocusGained
        
        if(new String (InsertConfSenhaC.getPassword()).equals("Confirmar Senha")){
        
            InsertConfSenhaC.setText(null);
            InsertConfSenhaC.requestFocus();
            
            InsertConfSenhaC.setEchoChar('*');
            
            InsertConfSenhaC.setForeground(new Color(0, 0, 0));
        
        }
        
    }//GEN-LAST:event_InsertConfSenhaCFocusGained

    private void InsertConfSenhaCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertConfSenhaCFocusLost
        
        if(new String (InsertConfSenhaC.getPassword()).equals("")){
        
            InsertConfSenhaC.setText("Confirmar Senha");
            InsertConfSenhaC.setForeground(new Color(0, 0, 0));
            
        }
        if(new String (InsertConfSenhaC.getPassword()).equals("Confirmar Senha")){
        
            InsertConfSenhaC.setEchoChar('\u0000');
            InsertConfSenhaC.setForeground(new Color(153, 153, 153));
            
        }
        
    }//GEN-LAST:event_InsertConfSenhaCFocusLost

    private void InsertConfSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertConfSenhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertConfSenhaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    public JTextField getInsertEmailC() {
        return InsertEmailC;
    }

    public void setInsertEmailC(JTextField InsertEmailC) {
        this.InsertEmailC = InsertEmailC;
    }

    public JTextField getInsertNomeC() {
        return InsertNomeC;
    }

    public void setInsertNomeC(JTextField InsertNomeC) {
        this.InsertNomeC = InsertNomeC;
    }

    public JPasswordField getInsertSenhaC() {
        return InsertSenhaC;
    }

    public void setInsertSenhaC(JPasswordField InsertSenhaC) {
        this.InsertSenhaC = InsertSenhaC;
    }

    public JPasswordField getInsertConfSenhaC() {
        return InsertConfSenhaC;
    }

    public void setInsertConfSenhaC(JPasswordField InsertConfSenhaC) {
        this.InsertConfSenhaC = InsertConfSenhaC;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarTela2;
    private javax.swing.JPasswordField InsertConfSenhaC;
    private javax.swing.JTextField InsertEmailC;
    private javax.swing.JTextField InsertNomeC;
    private javax.swing.JPasswordField InsertSenhaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}